version: '3.4'
x-default-environment:
  &default-environment
    - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
    - REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
    - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
    - REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}
    - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
    - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
    - REACT_APP_MEASUREMENT_ID=${REACT_APP_MEASUREMENT_ID}
    
services:
  
  auth-frontend:
    container_name: auth_frontend_web
    image: auth-frontend:development
    environment: *default-environment 
    restart: 'no'
    build:
        context: .
        dockerfile: ./Dockerfile
        target: development
    volumes:
        - .:/code
    ports:
      - "3000:3000"
    command: npm start
  
  