version: '3.4'
x-default-environment:
  &default-environment
    - MONGO_USERNAME=${MONGO_USERNAME}
    - MONGO_PASSWORD=${MONGO_PASSWORD} 
    - MONGO_HOST=${MONGO_HOST}
    - MONGO_PORT=${MONGO_PORT}
    - MONGO_DB=${MONGO_DB}
    - MONGO_PROTOCOL=${MONGO_PROTOCOL}
    - ENVIRONMENT=${ENVIRONMENT}
    - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    
services:
    
  tasks-mongo:
    container_name: tasks_mongo 
    image: mongo:4.4.8
    hostname: mongo
    restart: "no"
    ports:
      - "27018:27018"  # just for local dev 
    volumes:
      - mongodata:/data/db

  tasks-api:
    container_name: tasks_service
    image: tasks:development
    environment: *default-environment 
    restart: 'no'
    build:
        context: .
        dockerfile: ./Dockerfile
        target: development
    volumes:
        - .:/code
    ports:
      - "8001:8001"
    command: uvicorn tasks.main:app --host=0.0.0.0 --port=8001 --reload
    depends_on:
      - tasks-mongo
  
volumes:
  mongodata:
  