version: '3.4'
x-default-environment:
  &default-environment
    - MONGO_USERNAME=${MONGO_USERNAME}
    - MONGO_PASSWORD=${MONGO_PASSWORD} 
    - MONGO_HOST=${MONGO_HOST}
    - MONGO_PORT=${MONGO_PORT}
    - MONGO_DB=${MONGO_DB}
    - MONGO_PROTOCOL=${MONGO_PROTOCOL}
    - ENVIRONMENT=${ENVIRONMENT}
    - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    
services:
    
  users-mongo:
    container_name: users_mongo 
    image: mongo:4.4.8
    hostname: mongo
    restart: "no"
    ports:
      - "27017:27017"  # just for local dev 
    volumes:
      - mongodata:/data/db

  users-api:
    container_name: users_service
    image: users:development
    environment: *default-environment 
    restart: 'no'
    build:
        context: .
        dockerfile: ./Dockerfile
        target: development
    volumes:
        - .:/code
    ports:
      - "8000:8000"
    command: uvicorn users.main:app --host=0.0.0.0 --port=8000 --reload
    depends_on:
      - users-mongo
  
volumes:
  mongodata:
  